---
deployment:
    tasks:    
          - export DEPLOYPATH=/home/imrankha/public_html/routine 
          - /bin/cp index.php $DEPLOYPATH 
          - /bin/cp style.css $DEPLOYPATH
          - /bin/cp -R image $DEPLOYPATH
